name: icecap 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pandas-datareader
  - matplotlib
  - polars
  - pyarrow
  - jinja2
  - ipywidgets
  - ipytree
  - pytest
  - streamlit
  - jupytext
